### ISSUE TITLE
internal/process/esm_loader

### ISSUE THREAD

**Issue by KemikalGeneral** [redis/redis-om-node#125]
Hi,

I followed along with [this](https://www.youtube.com/watch?v=KUfufrwpBkM&t=580s) (great) video, and added my server, client, entity, and entity-router just fine, but, when I import the router files into server.js, i get the following error:

```
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Emitted 'error' event on Commander instance at:
    at RedisSocket.<anonymous> (C:\Users\kemik\Documents\projects\Vindico\express-redis-om-workshop\node_modules\@node-redis\client\dist\lib\client\index.js:339:14)
    at RedisSocket.emit (node:events:527:28)
    at RedisSocket._RedisSocket_connect (C:\Users\kemik\Documents\projects\Vindico\express-redis-om-workshop\node_modules\@node-redis\client\dist\lib\client\socket.js:117:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Commander.connect (C:\Users\kemik\Documents\projects\Vindico\express-redis-om-workshop\node_modules\@node-redis\client\dist\lib\client\index.js:162:9)
    at async file:///C:/Users/kemik/Documents/projects/Vindico/express-redis-om-workshop/om/client.js:7:1 {
    at RedisSocket._RedisSocket_connect (C:\Users\kemik\Documents\projects\Vindico\express-redis-om-workshop\node_modules\@node-redis\client\dist\lib\client\socket.js:117:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Commander.connect (C:\Users\kemik\Documents\projects\Vindico\express-redis-om-workshop\node_modules\@node-redis\client\dist\lib\client\index.js:162:9)
    at async file:///C:/Users/kemik/Documents/projects/Vindico/express-redis-om-workshop/om/client.js:7:1 {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

I thought it might be something to do with my config (although, there's not much there), so I cloned the repo, and get the same error. If I comment out the router imports in server.js, it runs fine, but crashes when I add them back in!?

I've seen lots of people say this issue is to do with the imported file extensions, but they're all in order :(

I've been going around in circles for about a day now, so any help would be great.

Thanks,

---

Windows 11 & MacOS
Node v16..16.0
npm v8.11.0

**Comment by guyroyse** [comment]
This sounds like a networking issue to me. Are you able to connect to Redis any other way?

**Comment by KemikalGeneral** [comment]
Hi @guyroyse, thanks for the suggestion.

Yes, I'm a numpty and was using the wrong host:port combination for Redis 🙄 

All the best.

**Comment by guyroyse** [comment]
No worries! Happens to the best of us.
