### ISSUE TITLE
this.schema.generateId is not a function

### ISSUE THREAD

**Issue by Otumian-empire** [redis/redis-om-node#131]
I wrote an article on this issue I have been facing. [article on dev.to](https://dev.to/otumianempire/i-am-doing-redis-or-what-598j)

I added the files from the old project and recreated the `model` folder as `db`. I _unistalled_ `redis-om` verson `0.3.6` and _installed_ version `0.1.5`. I hit the endpoint to create an admin and this was the log.

```sh
{"date":"Sun Aug 21 2022 16:05:39 GMT+0000 (Greenwich Mean Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: The field 'paidAt' is configured with a type of 'date'. Valid types include 'array', 'boolean', 'number', and 'string'.\nError: The field 'paidAt' is configured with a type of 'date'. Valid types include 'array', 'boolean', 'number', and 'string'.\n    at Schema.validateFieldDef (/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/schema/schema.js:84:19)\n    at Schema.defineProperties (/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/schema/schema.js:32:18)\n    at new Schema (/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/schema/schema.js:15:14)\n    at file:///home/user/Projects/web/ARMS-redis/src/db/schema/cash.schema.js:25:16\n    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)\n    at async Promise.all (index 0)\n    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)\n    at async loadESM (node:internal/process/esm_loader:88:5)\n    at async handleMainPromise (node:internal/modules/run_main:61:12)","os":{"loadavg":[1.71,1.92,1.59],"uptime":179703.37},"process":{"argv":["/home/user/.nvm/versions/node/v16.15.0/bin/node","/home/user/Projects/web/ARMS-redis/src/index.js"],"cwd":"/home/user/Projects/web/ARMS-redis","execPath":"/home/user/.nvm/versions/node/v16.15.0/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":239734,"external":1656558,"heapTotal":68870144,"heapUsed":49024800,"rss":113688576},"pid":125259,"uid":1000,"version":"v16.15.0"},"stack":"Error: The field 'paidAt' is configured with a type of 'date'. Valid types include 'array', 'boolean', 'number', and 'string'.\n    at Schema.validateFieldDef (/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/schema/schema.js:84:19)\n    at Schema.defineProperties (/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/schema/schema.js:32:18)\n    at new Schema (/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/schema/schema.js:15:14)\n    at file:///home/user/Projects/web/ARMS-redis/src/db/schema/cash.schema.js:25:16\n    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)\n    at async Promise.all (index 0)\n    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)\n    at async loadESM (node:internal/process/esm_loader:88:5)\n    at async handleMainPromise (node:internal/modules/run_main:61:12)","trace":[{"column":19,"file":"/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/schema/schema.js","function":"Schema.validateFieldDef","line":84,"method":"validateFieldDef","native":false},{"column":18,"file":"/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/schema/schema.js","function":"Schema.defineProperties","line":32,"method":"defineProperties","native":false},{"column":14,"file":"/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/schema/schema.js","function":"new Schema","line":15,"method":null,"native":false},{"column":16,"file":"file:///home/user/Projects/web/ARMS-redis/src/db/schema/cash.schema.js","function":null,"line":25,"method":null,"native":false},{"column":25,"file":"node:internal/modules/esm/module_job","function":"ModuleJob.run","line":198,"method":"run","native":false},{"column":null,"file":null,"function":"async Promise.all","line":null,"method":"all","native":false},{"column":24,"file":"node:internal/modules/esm/loader","function":"async ESMLoader.import","line":385,"method":"import","native":false},{"column":5,"file":"node:internal/process/esm_loader","function":"async loadESM","line":88,"method":null,"native":false},{"column":12,"file":"node:internal/modules/run_main","function":"async handleMainPromise","line":61,"method":null,"native":false}]}
```

Well, it has something to do with the type, `date`.

I went back to [this](https://github.com/redis-developer/express-redis-om-workshop/blob/solution/package.json) project on GitHub and so I installed that version instead.

```sh
{"level":"info","message":"Redis server connected"}
{"level":"info","message":"server started on port 3000"}
{"level":"error","message":"this.schema.generateId is not a function"}
TypeError: this.schema.generateId is not a function
    at Repository.createEntity (/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/repository/repository.js:43:30)
    at Repository.createAndSave (/home/user/Projects/web/ARMS-redis/node_modules/redis-om/dist/repository/repository.js:63:27)
    at create (file:///home/user/Projects/web/ARMS-redis/src/controller/admin.controller.js:57:31)
{"contentLength":"47","level":"info","message":"HTTP Log","method":"POST","responseTime":122.367,"status":200,"timestamp":"Sun Aug 21 2022 16:20:31 GMT+0000 (Greenwich Mean Time)","url":"/admin"}
```

Back to square one.

I think I should switch to typescript. I will switch to typescript before I sleep and if it doesn't work, at least I learnt something.

I am ubuntu 20.04, node v16.15.0, npm 8.10.0, Redis server v=7.0.0, redis js 4.2.0, redis-om js [0.1.5, 0.2.0, 0.3.6].

**Comment by guyroyse** [comment]
The date type was added later. The downgrade from 0.3.6 to 0.1.5 caused this issue. It's probable that the example code at https://github.com/redis-developer/express-redis-om-workshop/blob/solution/package.json, which uses Redis OM 0.2.0, is not compatible with 0.3.6.

Redis OM is still under development, which is why the version number starts with a zero. Think of 0.1.*, 0.2.*, and 0.3.* as major releases that are not guaranteed to be backwards compatible. The canonical examples to use for the current version of Redis OM are in the README in this repository.

**Comment by Otumian-empire** [comment]
So deleting the node_modules would have done the resolved the issue
regardless of the version?

**Comment by guyroyse** [comment]
Probably. Although `npm uninstall redis-om` should remove it from `node_modules` too.
