### ISSUE TITLE
entity.toRedisJson is not a function

### ISSUE THREAD

**Issue by ericlovescode** [redis/redis-om-node#144]
I called fetch to return a JSON object, changed one field, and then called 'save' and this is the error:
/home/xxxx/node/acg/node_modules/redis-om/dist/index.js:973
    await this.client.jsonset(entity.keyName, entity.toRedisJson());
                                                     ^
TypeError: entity.toRedisJson is not a function
    at JsonRepository.writeEntity (/home/xxxx/node/acgt/node_modules/redis-om/dist/index.js:973:54)
    at JsonRepository.save (/home/xxxx/node/acg/node_modules/redis-om/dist/index.js:911:16)
    at /home/xxxx/node/acg/routes/xero-api.js:222:58
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ericlovescode** [comment]
Invalid. I was fetching the entity, then using .toJSON to format it, making the change, and then trying to .save(). I understand now that I have to make the change on the actual entity JSON.
