### ISSUE TITLE
Redis-om not working when redis is in legacy mode

### ISSUE THREAD

**Issue by datmax** [redis/redis-om-node#147]
I have an application with Redis, connect-redis for session storage and Redis-om: writing on the req.session object is allowed only with Redis set to "legacymode:true", but if i set Redis in legacy mode i can't perform searches using redis om.
Am i getting everything wrong or is this an actual problem? In the meantime, i'll directly save the session Id in localstorage and save it in the user object in my redis db.

An example of error when using redis in legacy mode:

```
const [count] = this.results;
                    ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at JsonSearchResultsConverter.get count [as count] (/Users/bibibi/Documents/projects/superserver/node_modules/redis-om/dist/index.js:441:21)
    at Search.count (/Users/bibibi/Documents/projects/superserver/node_modules/redis-om/dist/index.js:653:110)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Search.returnCount (/Users/bibibi/Documents/projects/superserver/node_modules/redis-om/dist/index.js:731:12)
```

My Redis client configuration: 
```
import { Client } from 'redis-om';
import { createClient } from "redis";

const url = "redis://localhost:6379";
export const connection = createClient({url:url, legacyMode:true})


connection.on('error', (err) => console.log('Redis Client Error', err));
await connection.connect();


const client = await new Client().use(connection);


export default client
```

**Comment by datmax** [comment]
> I've not tried using Redis OM with legacy mode and it wasn't taken into consideration when I wrote it. Might be a nice feature but it's not at the top of the priority list. And, it could work already anyhow. I can think of two approaches worth trying:
> 
> 1. Try passing in `connection.v4` instead of just `connection`.
> 2. Create a separate connection for connect-redis that uses legacy mode.
> 
> The latter will almost certainly work but has the obvious disadvantage of doubling the number of connections to Redis. I would expect the former to work but haven't tried it.

Thank you for the quick response! I thought about the second approach too, but it's more linear(at least for my brain) to just skip the session thing and use raw localstorage and embedding the sessionId in the User model.

I'll update this answer once i try ```connection.v4``` to let everyone know if it works out. Have a nice day and thanks for this library!
